version: '3.7'
services:

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    restart: always
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  kafka:
    image: 'bitnami/kafka:latest'
    restart: always
    depends_on:
      - zookeeper
    environment:
     - ALLOW_PLAINTEXT_LISTENER=yes
     - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
     - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
    ports:
      - 9092:9092
    # command: 
    #   - /opt/bitnami/kafka/bin/kafka-topics.sh --create --bootstrap-server localhost:9092 --replication-factor 1 --partitions 2 --config retention.ms=259200000 --topic nuevos-miembros
    #   - /opt/bitnami/kafka/bin/kafka-topics.sh --create --bootstrap-server localhost:9092 --replication-factor 1 --partitions 2 --config retention.ms=259200000 --topic topic-ventas
    #   - /opt/bitnami/kafka/bin/kafka-topics.sh --create --bootstrap-server localhost:9092 --replication-factor 1 --partitions 2 --config retention.ms=259200000 --topic topic-coordenadas
    #   - /opt/bitnami/kafka/bin/kafka-topics.sh --create --bootstrap-server localhost:9092 --replication-factor 1 --partitions 2 --config retention.ms=259200000 --topic topic-stock

  server-crud:
    container_name: server-crud
    build: ./server-crud
    depends_on:
      - zookeeper
      - kafka
    environment:
      PORT: 3000
      kafkaHost: kafka:9092
    ports:
      - "3000:3000" 
    volumes:
      - "./server-crud/src:/app/src"

  server-ventas:
    container_name: server-ventas
    build: ./server-ventas
    depends_on:
      - zookeeper
      - kafka
    environment:
      PORT: 4000
      kafkaHost: kafka:9092
    ports:
      - "4000:4000" 
    volumes:
      - "./server-ventas/src:/app/src"

  server-miembros:
    container_name: server-miembros
    build: ./server-miembros
    depends_on:
      - zookeeper
      - kafka
    environment:
      PORT: 5000
      kafkaHost: kafka:9092
    ports:
      - "5000:5000" 
    volumes:
      - "./server-miembros/src:/app/src"
  
  server-ubicacion:
    container_name: server-ubicacion
    build: ./server-ubicacion
    depends_on:
      - zookeeper
      - kafka
    environment:
      PORT: 6000
      kafkaHost: kafka:9092
    ports:
      - "6000:6000" 
    volumes:
      - "./server-ubicacion/src:/app/src"

  server-stock:
    container_name: server-stock
    build: ./server-stock
    depends_on:
      - zookeeper
      - kafka
    environment:
      PORT: 7000
      kafkaHost: kafka:9092
    ports:
      - "7000:7000" 
    volumes:
      - "./server-stock/src:/app/src"

      