version: '3.7'
services:

  zookeeper:
    image: 'bitnami/zookeeper:3.7.0'
    restart: always
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  kafka:
    image: 'bitnami/kafka:2.8.1'
    restart: always
    depends_on:
      - zookeeper
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
    ports:
      - 9092:9092

  server-crud:
    container_name: server-crud
    build: ./server-crud
    depends_on:
      - zookeeper
      - kafka
    environment:
      PORT: 3000
      kafkaHost: kafka:9092
    ports:
      - "3000:3000" 
    volumes:
      - "./server-crud/src:/app/src"

  server-ventas:
    container_name: server-ventas
    build: ./server-ventas
    depends_on:
      - zookeeper
      - kafka
    environment:
      PORT: 4000
      kafkaHost: kafka:9092
    ports:
      - "4000:4000" 
    volumes:
      - "./server-ventas/src:/app/src"

      